### ISSUE TITLE
Get Light/Dark mode preference from the browser

### ISSUE THREAD

**Issue by Wabuo** [Zavy86/WikiDocs#102]
### Describe the feature

It would be nice if WikiDoks would honour the preferred light/dark mode setting from the browser.

This would mean people with a dark theme get the dark version, while people with a light theme still get the light version.

### Extra fields

- [ ] I'd like to work on this feature

**Comment by leomoon** [comment]
I was looking into this.

the main WikiDocs part is easy. I already have it done by putting all css into styles.css and putting dark styles inside `@media (prefers-color-scheme: dark) {}`.

Main issue are these two which I'm not sure how to load proper styles the most optimized way yet:
```html
<link type="text/css" rel="stylesheet" href="<?= $APP->PATH ?>helpers/highlightjs-11.9.0/css/<?= ($APP->DARK?"monokai-sublime":"default") ?>.min.css" media="screen,projection">
<script>mermaid.initialize({ startOnLoad: true,'theme': <?= ($APP->DARK?"'dark'":"'neutral'") ?>});</script>
```
