### ISSUE TITLE
Wikidocs.it webpage displaying porn. 

### ISSUE THREAD

**Issue by ChristopherEverett** [Zavy86/WikiDocs#103]
### Describe your issue

The wikidocs.it home page is displaying a pornographic image. The sidebar also now has a menu options for "pornsite". The info bar at the bottom of the site says the last change was made today, 2/4/24.

Im not sure if this is a new direction this project will be going in, but I thought I'd make sure you're aware of these changes. 

### Device and settings

OS: Ubuntu, Android. Browser: Chrome, Firefox

### Steps to reproduce

1. Go to wikidocs.it

### Extra fields

- [ ] I'd like to work on this issue

**Comment by Zavy86** [comment]
yes.. the website was hacked!
i have remove porn image and link..

**Comment by Zavy86** [comment]
8e7ad7a4c67e2be48675f61f3179f85faae54b42

oh my god!

**Comment by Zavy86** [comment]
fixed in 1.0.15
