### ISSUE TITLE
Anyone can edit my wikidocs

### ISSUE THREAD

**Issue by AdamJesus** [Zavy86/WikiDocs#107]
### Describe your issue

Don't require `authentication code`, anyone can modify wikidocs.

### Device and settings

WikiDocs-1.0.14

### Steps to reproduce

1. Just enter `https://domain.com/settings.php`.
2.  Modify `authentication code` and save.
3.  Enter `authentication code` that modified.
4.  Modify and delete any page.

### Extra fields

- [ ] I'd like to work on this issue

**Comment by Zavy86** [comment]
i love you!!!
you find the big bug! -> https://github.com/Zavy86/WikiDocs/issues/103

**Comment by Zavy86** [comment]
8e7ad7a4c67e2be48675f61f3179f85faae54b42

oh my god!

**Comment by Zavy86** [comment]
fixed in 1.0.15
