### ISSUE TITLE
Authentication problem

### ISSUE THREAD

**Issue by gimmel** [Zavy86/WikiDocs#108]
### Describe your issue

I set the EDITCODE in config.inc.php to something (437B930DB84B8079C2DD804A71936B5F) and was not able to login.

Took me a while to find out that only lowercase is allowed as a MD5 checksum. Both, EDITCODE and the Authentication input should be lowercased before verifying them.

### Device and settings

Every server, every browser

### Steps to reproduce

Just follow the setup guide at https://www.wikidocs.it/setup
„Edit the configuration file nano datasets/config.inc.php“

1. Generate a MD5 of you password with a tool (that mostly outputs uppercase)
2. Paste it in EDITCODE in config.inc.php
3. Try to login

### Extra fields

- [ ] I'd like to work on this issue

**Comment by Zavy86** [comment]
Fixed in release 1.0.17

**Comment by gimmel** [comment]
Thank you very much.
