### ISSUE TITLE
details not working

### ISSUE THREAD

**Issue by BarneyOldman** [Zavy86/WikiDocs#115]
### Describe your issue

the DropDown funkction is not working. In the Preview it shows the Dropdown but not after saving the page

### Device and settings

docker 1.0.18

### Steps to reproduce

```
<details>
<summary>Dropdown</summary>

test text

</details>
```

### Extra fields

- [ ] I'd like to work on this issue

**Comment by Zavy86** [comment]
hello, it works on the demo, can you try it?
are you using the latest release?

![image](https://github.com/user-attachments/assets/a8b50b60-af3e-4dd1-aa5c-6d3427013171)
