### ISSUE TITLE
Avoid MD5 hashes for passwords

### ISSUE THREAD

**Issue by TheNeoBurn** [Zavy86/WikiDocs#118]
### Summary
The edit and view codes are stores as MD5 hashes which are fundamentally insecure without a salt.

### Details
The code uses `md5()` the hash the edit and view code password. This is not considered secure anymore. PHP offers `password_hash()` and `password_verify()` to use newer more secure hashing algorithms.

### Impact
If an attacker manages to get get access to the content of `datasets/config.inc.php` it is likely the attacker can also retrieve the passwords by using rainbow tables or a list of hashes for known passwords.

### CWE
Use of Weak Hash (CWE-328)

### Device and settings

Debian, nginx, php8.1

### Steps to reproduce

1. Install and configure an instance of WikiDocs

### Extra fields

- [ ] I'd like to work on this issue

**Comment by Zavy86** [comment]
fixed in 1.0.20
