### ISSUE TITLE
SearchBox placeholder text color

### ISSUE THREAD

**Issue by vCoDMods** [Zavy86/WikiDocs#127]
Hello,

i have tried to change the color of placeholder in searchbox, but every css code gets ignored completly and the text stays light grey.

**Comment by Zavy86** [comment]
can you share your `styles/styles-custom.css` code please?

**Comment by Zavy86** [comment]
where is the search placeholder style?

**Comment by Zavy86** [comment]
`#nav-mobile li.search .search-wrapper input#search::placeholder {
  color: red;
}`

this worked for me

**Comment by Zavy86** [comment]
if your wiki is public and you want to appear here give me your link! ;)

https://wikidocs.it/examples
