### ISSUE TITLE
Video Support - YouTube and Vimeo

### ISSUE THREAD

**Issue by leomoon** [Zavy86/WikiDocs#136]
- embed youtube videos (although I haven't found a valid MD way to do it yet... so not sure if it can be done)

_Originally posted by @SvenMazet in https://github.com/Zavy86/WikiDocs/issues/75#issuecomment-1992485692_

**Comment by Zavy86** [comment]
rocket leomoon! ;)

**Comment by leomoon** [comment]
I wrote yet another parsedown extension!: https://github.com/leomoon-studios/ParsedownPlus
![image](https://github.com/Zavy86/WikiDocs/assets/3268946/91bed4e8-e5c0-42c1-8e5a-1d8bd936b2e6)

**Comment by Zavy86** [comment]
you are on fire!

**Comment by ffiesta** [comment]
Hi @leomoon,

Now video support stay inline in browser  

![image](https://github.com/Zavy86/WikiDocs/assets/25620658/86a59a60-1700-47c4-aede-e3e8bd2341e4)
 
To other type videos I add extension and mimetype to upload zone.

Thanks,

**Comment by leomoon** [comment]
Yea, only YouTube and Vimeo are supported right now.

I might add more later.
