### ISSUE TITLE
wikidocs.it freezing on android scroll

### ISSUE THREAD

**Issue by ffiesta** [Zavy86/WikiDocs#152]
### Describe your issue

Hi, a few minutes I go to wikidocs.it to check htaccess configuration and it freezing on scroll.

Until it load, I can scroll, after load freeze, tested android samsung M21 and A35 Chrome and brave.

Another issue only on brave when I make a url copy it show http://wikidocs.it/ instead https://wikidocs.it, check brave snapshot.

![Brave snapshot](https://github.com/user-attachments/assets/1ec31883-ab6b-4db1-b253-c2783469bacc)

### Device and settings

Samsung M21 and A35

### Steps to reproduce

Open website and try to scroll down

### Extra fields

- [ ] I'd like to work on this issue

**Comment by leomoon** [comment]
The deployment seems to be using an old build. Cuz the tables should be 100% and they are not here.

**Comment by leomoon** [comment]
Yea, wikidocs.it is at version 1.0.30 which is older: 
https://wikidocs.it/VERSION

**Comment by Zavy86** [comment]
yes the update of the website is still manual..
tomorrow I will update it!

**Comment by ffiesta** [comment]
Solved
