### ISSUE TITLE
Cpanel Error 404 - create doc with more than 3 words

### ISSUE THREAD

**Issue by ffiesta** [Zavy86/WikiDocs#157]
### Describe your issue

When i try to create a doccument with 3 letters i receive a error 404 (not found) and (403 forbiden), associated to **%20** in middle of second space.

With error on screen if I change **%20** to **-** i can add de document.

Wikidocs version 1.0.37.

### Device and settings

Window 10, 11 and android (brave, edge and chrome browser)

### Steps to reproduce

1. try create a document with 3 letters.

### Screenshots (optional)

- Edit document add
![error_3 letters name 1](https://github.com/user-attachments/assets/9bc1b48b-c642-4b02-83b8-336d0648904c)  

- Error after save
![error_3 letters name 2](https://github.com/user-attachments/assets/92bcb15e-4eab-42ca-82dd-bcc3ab3b4192)

NOTE: This can be a cpanel block. There is a way that can i use to identify the problem, because localy it work?

### Extra fields

- [ ] I'd like to work on this issue

**Comment by ffiesta** [comment]
Hi,

After some web read, i find that the probem can the space charater, 

 **space character is not a standard space (U+0020), but rather a non-breaking space (U+00A0) or another type of whitespace character**

And if i change the `(" ", "-")` to `(/\s+/g, '-')` can solve the problem.

Here the explanation and complete code (Line 380 - template.inc.php file)

- `\s+` matches one or more whitespace characters (including spaces, tabs, and non-breaking spaces)  
- `g` flag at the end of the regex pattern makes the replacement global, so all whitespace characters are replaced, not just the first one

Complete line code: `new_path = new_path.replace(/\s+/g, '-').toLowerCase() + "?edit";` 

I make a rapid test and it works

**Comment by ffiesta** [comment]
Hi, after more tests i find that %20  error occurs when we try to create a doc with some special character like `some special / caracter`. This error stay on bowser cache and cause future errors or unknown errors.

Adding my solution wikidocs don't give error and informa that will create doc `some-` instead of `some-special-character`

**Comment by Zavy86** [comment]
#159

**Comment by Zavy86** [comment]
solved right?

**Comment by ffiesta** [comment]
> solved right?

yap
