### ISSUE TITLE
cpanel - Upload file-error

### ISSUE THREAD

**Issue by ffiesta** [Zavy86/WikiDocs#158]
### Describe your issue

When i try to upload a *.pdf file i receive "file-error" message, and php won't create log-error! 

How can i check the problem, if cpanel won't show error!?

### Device and settings

windows 10, 11, brave chrome

### Steps to reproduce

try to upload file

### Screenshots (optional)

![error_file-error](https://github.com/user-attachments/assets/4ed6835e-bbf2-42dd-a4c4-774094e0a8f5)

### Extra fields

- [ ] I'd like to work on this issue

**Comment by ffiesta** [comment]
Solved error, enable php options and file limits

**Comment by ItsMeRitch** [comment]
@ffiesta How were you able to solve this, I'm not sure where or what to edit

**Comment by ItsMeRitch** [comment]
> > @ffiesta How were you able to solve this, I'm not sure where or what to edit
> 
> If you have a cpanel you need to unlock the max size upload, on php.
> 
> But were you have the problem.

Thanks, I'm just using the basic docker setup and have check the /etc/php7/php.ini file and it has everything enabled and on. I must be doing something wrong lol

**Comment by Zavy86** [comment]
we need to provide a settings also for that..
we can set the max file size to the dockerfile to the max value or unlimited and then manage it only by wikidocs submit script
