### ISSUE TITLE
Direct access to documents without password

### ISSUE THREAD

**Issue by ffiesta** [Zavy86/WikiDocs#162]
### Describe your issue

If we know how wikidocs works and if we know the folder name structure we can have direct access to wikidocs content.md doc file, or other file without password

1. If we try to access to https://example.com/syntax wikidocs ask the read or admin password.

2. But if we use url https://example.com/datasets/documents/syntax/content.md  we view content the file as raw.

### Device and settings

Multiple devices

### Steps to reproduce

See describe issue

### Extra fields

- [ ] I'd like to work on this issue

**Comment by leomoon** [comment]
good catch.

We could do one of these (not tested).

using apache:
```
<FilesMatch "\.(md)$">
    Require all denied
</FilesMatch>
```

or nginx:
```
server {
    # Other server configurations...

    location ~* \.md$ {
        deny all;
    }

    # Other location blocks...
}
```

Or additional checks in `Document.class.php`.

**Comment by ffiesta** [comment]
After thinking a little, I think the best way is to force wikidocs to validate the user status / password used in case everything is private.  Despite searching, I was unable to find a place to add user state validations.

**Comment by ffiesta** [comment]
> good catch.
> 
> We could do one of these (not tested).
> 
> using apache:
> 
> ```
> <FilesMatch "\.(md)$">
>     Require all denied
> </FilesMatch>
> ```
> 
> or nginx:
> 
> ```
> server {
>     # Other server configurations...
> 
>     location ~* \.md$ {
>         deny all;
>     }
> 
>     # Other location blocks...
> }
> ```
> 
> Or additional checks in `Document.class.php`.
> 
> I prefer apache and nginx way.

Tested on apache and cpanel, and works.

Please someone test on ngnix.

- This solve 1rst problem content.md files but don't prevent acess to other file types, like pdf or txt ....

**Comment by leomoon** [comment]
how about this:
```
<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteBase /

    # Block direct access to .md files
    RewriteRule ^datasets/documents/.*\.md$ - [F,L,NC]

    # Handle all other requests
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^(.*)$ index.php?doc=$1 [NC,L,QSA]
</IfModule>
```

**Comment by ffiesta** [comment]
Hi,

- next code solve when wikidocs has on root folder
```
# Block direct access to .md files
    RewriteRule ^datasets/documents/.*\.md$ - [F,L,NC]
```  

- next code solve when wikidocs has on root/subfolder
```
<FilesMatch "\.(md)$">
    Require all denied
</FilesMatch>
```

About another files , after thinking you are write.

**Comment by Zavy86** [comment]
maybe it would be a good idea to make a rule that blocks access to any file and manage everything through internal routing? both for images and any attachments?

**Comment by Zavy86** [comment]
maybe we could block all access to the /datasets/ directory but we need to change routing for static files..

https://demo.wikidocs.it/datasets/documents/ciao/0b752b26a1ba34b6316065f2a4bf6b19.png

should become

https://demo.wikidocs.it/ciao/0b752b26a1ba34b6316065f2a4bf6b19.png

![image](https://github.com/user-attachments/assets/c8ab6fa3-63ef-4299-8400-ff7c55f01baf)

**Comment by ffiesta** [comment]
Hi @Zavy86 

- Inspite of using next code, on htaccess

```
 # Block direct access to .md files
    RewriteRule ^datasets/documents/.*\.md$ - [F,L,NC]
```  

- how about using (but i can figured how to do this)

```
# check for the session variable, to show files
	RewriteRule ^datasets/documents/(.*)$ classes/session.class.php?file=$1 [L]
```
or create check_access.php file to verify login token

```
# check for the session variable, to show files
	RewriteRule ^datasets/documents/(.*)$ check_access.php?file=$1 [L]
```

**Comment by leomoon** [comment]
Ppl should not be thinkering like that.

We should just redirect to / if any .md file is accessed I think.

**Comment by ffiesta** [comment]
Hi to all,




> Ppl should not be thinkering like that. There's no reason to do that. They have editor and viewer...
> 
> We should just redirect to / if any .md file is directly accessed.

Hi to all,

This solution won't work when wikidocs is on a subfolder.

**Comment by ffiesta** [comment]
Yop see:

```  
<IfModule mod_rewrite.c>
	RewriteEngine On
	RewriteBase /wikidocs42/
	RewriteCond %{REQUEST_URI} \.md$ [NC]
	RewriteRule ^.*$ / [R=301,L]
	RewriteCond %{REQUEST_FILENAME} !-f
	RewriteRule ^(.*)$ index.php?doc=$1 [NC,L,QSA]
</IfModule>
```  
What i made wrong?


Another thing because this issue, I create a simple Datasets.class.php file based on wiki37 that use session.class.php to verify if user is logged or not, and it won't work when wikidocs is on subfolder, but it should work. After reading some websites they say that when wikidocs create php_session creates it thinking that the website is in the root folder, and won't add /subfolder/ to directory url or path. The say that my script can't read php_session because my script search for php_session with complete url wikidocs.it/subfolder/... and php session only have wikidocs.it/... .

Based on this and on the previous problem with attachments I think the creation of url have some problems and i dont are isolated in folder/subfolder or user.
