### ISSUE TITLE
Blank page after latest update

### ISSUE THREAD

**Issue by anonymouz-trash** [Zavy86/WikiDocs#163]
### Describe your issue

After the latest update I just receive a white blank page.
On status monitoring with Homepage (gethomepage.dev) I see a "500 Internal Server Error".

In docker container itself under /var/log/apache2/error.log:
```
[Thu Aug 22 13:30:45.341641 2024] [php7:error] [pid 17] [client 172.25.0.1:45546] PHP Fatal error:  Uncaught Exception: The user is probably trying to create the document outside of the documents dataset in /var/www/localhost/htdocs/classes/Document.class.php:99\nStack trace:\n#0 /var/www/localhost/htdocs/index.php(27): Document->__construct()\n#1 {main}\n  thrown in /var/www/localhost/htdocs/classes/Document.class.php on line 99
```
Before then everything worked fine.

I already did browser cache cleaning.
Is there any thing I can do to support you with solving this issue?

I'm new to GitHub issue reporting and excuse any inconvenience due to any common rules of error reporting.

### Device and settings

raspberry pi and docker

### Steps to reproduce

Just updated container image automatically with watchtower or did a docker compose up -d --force-recreate.

### Extra fields

- [ ] I'd like to work on this issue

**Comment by anonymouz-trash** [comment]
I tried to recreate the container with `docker compose up -d --force-recreate' and also moved the datasets folder/volume to elsewhere.
I get the initializing page (setup.php) and fill out the form and what to access the wiki. After that:
```
[Thu Aug 22 14:01:32.090884 2024] [php7:error] [pid 22] [client 192.168.178.16:58556] PHP Fatal error:  Uncaught Exception: The user is probably trying to create the document outside of the documents dataset in /var/www/localhost/htdocs/classes/Document.class.php:99\nStack trace:\n#0 /var/www/localhost/htdocs/index.php(27): Document->__construct()\n#1 {main}\n  thrown in /var/www/localhost/htdocs/classes/Document.class.php on line 99, referer: http://192.168.178.4:4242/setup.php?act=conclude
```

**Comment by Zavy86** [comment]
@dvisentin-freelance there might be a problem, can you take a look or should I rollback?

**Comment by Zavy86** [comment]
For now I have removed that control, we will then see if we can integrate it with the necessary tests.

fix in 1.0.39

**Comment by dvisentin-freelance** [comment]
Ok. The problem is with the second commit. That check could potentially be moved downstream only in the places where it's really neaded, instead of doing it in the constructor.

What I was trying to do with that check was to prevent the user from saving the document outside the designated folder, for example manually editing the document id in the form.

![image](https://github.com/user-attachments/assets/3d2d4522-ba13-407a-a846-d679d1cca092)

**Comment by Zavy86** [comment]
we can add it before put_file_contents ?

**Comment by dvisentin-freelance** [comment]
Probably yes. I'll take a look later.

**Comment by dvisentin-freelance** [comment]
#168
