### ISSUE TITLE
More Docker tags

### ISSUE THREAD

**Issue by anonymouz-trash** [Zavy86/WikiDocs#165]
### Describe the feature

First of all thank you for your very fast support! Appreciate it very much!

Just for that case I thought about more docker tags like:

```
zavy86/wikidocs:dev
```
and
```
zavy86/wikidocs:stable
```

What do you think about? You would be able to testing things out before they go live in stable.

EDIT: FYI, everything works fine again. This tool is just awesome.

### Is your feature request related to a problem? (optional)

Yes, Issue Number: #163 

### Extra fields

- [ ] I'd like to work on this feature

**Comment by Zavy86** [comment]
if you are skilled with docker files you can contribute ;) it will be apreciated!

**Comment by anonymouz-trash** [comment]
> if you are skilled with docker files you can contribute ;) it will be apreciated!

I'm sorry therefor help is needed. I don't know. My guess is to create several branches called `dev` and `stable` and push it to docker hub as referred in the docs: [Publishing images to Docker Hub](https://docs.github.com/en/actions/use-cases-and-examples/publishing-packages/publishing-docker-images#publishing-images-to-docker-hub)
But I'm not experienced enough to tell you exactly how it works. Sorry.
