### ISSUE TITLE
Setup Script Failing

### ISSUE THREAD

**Issue by ItsMeRitch** [Zavy86/WikiDocs#167]
### Describe your issue

On first run, I'm getting the following error:

![Screenshot 2024-08-23 at 14 38 24](https://github.com/user-attachments/assets/04654e43-2ffa-45ea-a33b-a3201fa0731c)

### Device and settings

Ubuntu running docker

### Steps to reproduce

Run the docker app 

### Extra fields

- [ ] I'd like to work on this issue

**Comment by ffiesta** [comment]
Hi @ItsMeRitch, 

Are you trying to perform a new wikidocs installation or update!? 

Anyway based on you image you are trying to setup a new instalation, please add this file [sample.config.inc.php](https://github.com/Zavy86/WikiDocs/blob/master/datasets/sample.config.inc.php) to folder datasets, and try again.

**Comment by Zavy86** [comment]
link #164

**Comment by Zavy86** [comment]
fixed in 1.0.47
