### ISSUE TITLE
Undefined

### ISSUE THREAD

**Issue by ncopz** [Zavy86/WikiDocs#17]
How to fix it?
Thanks.

\xampp\htdocs\test\functions.inc.php on line 23

**Comment by Zavy86** [comment]
can you paste the full error?

**Comment by kleinechristoph** [comment]
I believe @ncopz is experiencing this error:
Warning :  Undefined variable $debug in C:\xampp\htdocs\test\functions.inc.php
referencing the session initialization checking for a debug variable to be set.

**Comment by Zavy86** [comment]
Ok, you can ignore this warning, we will fix it in the next release.
