### ISSUE TITLE
Wget wikidocs files

### ISSUE THREAD

**Issue by ffiesta** [Zavy86/WikiDocs#194]
### Describe your issue

When we use `wget.exe https://www.wikidocs.it/syntax` we can download all files with wget.

To prevent this we need to insert on htaccess file the code:

```
RewriteCond %{HTTP_USER_AGENT} wget.* [NC]
RewriteRule .* - [F,L]
``` 
[**in htaccess wikidocs**](https://github.com/Zavy86/WikiDocs/blob/master/sample.htaccess) 

<IfModule mod_rewrite.c>
	RewriteEngine On
	RewriteBase /  

        RewriteCond %{HTTP_USER_AGENT} wget.* [NC]
        RewriteRule .* - [F,L]

	RewriteCond %{REQUEST_URI} \.md$ [NC]
	RewriteRule ^.*$ / [R=301,L]
	RewriteCond %{REQUEST_FILENAME} !-f
	RewriteRule ^(.*)$ index.php?doc=$1 [NC,L,QSA]
</IfModule> 

Here the big list http://www.javascriptkit.com/howto/htaccess13.shtml  

### Device and settings

WIndows 10 Pro, Chrome browser

#### Download - COMPLETE
```
C:\TEMPPPPPPPPPPPPP\wget>wget.exe https://example.com/markdown-hacks
--2024-09-17 18:26:56--  https://example.com/markdown-hacks
Resolving example.com (example.com)... 94.46.169.171
Connecting to example.com (example.com)|94.46.169.171|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: 'markdown-hacks'

markdown-hacks                            [ <=>                                                                     ]   8,89K  --.-KB/s    in 0s

2024-09-17 18:26:56 (26,8 MB/s) - 'markdown-hacks' saved [9105]
```

#### Download - Blocked
```
C:\TEMPPPPPPPPPPPPP\wget>wget.exe https://example.com/markdown-hacks
--2024-09-17 18:28:35--  https://example.com/markdown-hacks
Resolving example.com (example.com)... 94.46.169.171
Connecting to example.com (example.com)|94.46.169.171|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2024-09-17 18:28:35 ERROR 403: Forbidden.

```

### Extra fields

- [ ] I'd like to work on this issue

**Comment by leomoon** [comment]
I don't see why that is a problem.

If we block with wget, there are a ton of other tools that can download and mask their agent to look like chrome or firefox...

**Comment by ffiesta** [comment]
> I don't see why that is a problem.
> 
> If we block with wget, there are a ton of other tools that can download and mask their agent to look like chrome or firefox...
> 
> And wget also supports agent masking.
> 
> ```
> wget --user-agent="Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"
> ```

Ok. But ... if wget can get all wikidocs files, why i protect wiki using password, or why prevent direct access to md files!?

**Comment by leomoon** [comment]
I added password for also viewing. Opened one of the docs in browser and it requested password to view...

I tried downloading with wget and the downloaded html file shows the password form, not the actual doc.

So from what I understand, wikidocs has protected the doc.

Am I understanding this wrong?

**Comment by ffiesta** [comment]
@leomoon ... in my test i ise protected wikidocs page and wget downloaded that. Perhaps my wget it's using cached page although I'm not logged! 

Thanks
