### ISSUE TITLE
Search Function broken?

### ISSUE THREAD

**Issue by StarRico** [Zavy86/WikiDocs#2]
Just leaving this here. Love this wiki but yes, the search is broken on it at the moment.

**Comment by janroden** [comment]
Thanks for the nice project!

Yes, the search function seems to be broken for me as well. 

If I type any search term into the search field on the left, that definitely exists with same spelling on pages, I always get "No results found for ...". Even if the search term is part of a title of a page, or even if the term is contained in the page currently open on the right.

**Comment by Zavy86** [comment]
i have tried in the demo website and seem not working in homepage but in other page is working for me..
i will check for the home page..

![Screenshot 2023-10-12 at 17 32 20](https://github.com/Zavy86/WikiDocs/assets/2051811/f34a3975-80cf-41ab-8bb6-ec94f15c10b0)

**Comment by balintbalazs** [comment]
I had the same experience on a local installation: generally search works, but in for content under `homepage/`.

**Comment by balintbalazs** [comment]
Awsome, thanks a lot!

**Comment by janroden** [comment]
Awesome! :) Thanks a lot for the fast response!

**Comment by janroden** [comment]
I can also confirm that the search works on pages that are *not* under the homepage. 

Another funny behavior of the search function I just noticed:

When I search for a word and write it in all lower-case letters, it also finds the appearances where the same word starts with upper-case letter (which is nice), but in the search results on the right side, it puts the word into the text everywhere as if it starts with lower-case even in occurrences where it actually starts with an upper-case letter :)

**Comment by Zavy86** [comment]
ok fixed all in 1.0.8 -> https://github.com/Zavy86/WikiDocs/commit/493e290362225072c49b5e7eea749778cfef5fdf

![image](https://github.com/Zavy86/WikiDocs/assets/2051811/b809f63e-d9d5-4a4c-b02a-ca5ada680e44)

**Comment by janroden** [comment]
That's great! :)  Thank you very much!
And have a nice day!
