### ISSUE TITLE
top button alignment

### ISSUE THREAD

**Issue by Zavy86** [Zavy86/WikiDocs#200]
### Describe your issue

maybe it would be better to align the top button with the structure?

and what do you think about putting an arrow pointing up instead of the top writing? so as to avoid having to do the translations?

![Screenshot 2024-10-04 at 09 55 29](https://github.com/user-attachments/assets/ce1b67dc-7a3a-49f4-94ab-82df2bd13afd)

### Device and settings

mac os, chrome

### Steps to reproduce

1. open the demo website
2. resize the window

### Screenshots (optional)

![Screenshot 2024-10-04 at 09 50 34](https://github.com/user-attachments/assets/f87e4ed1-2b84-406c-8de2-7cf9d706e24a)

### Extra fields

- [ ] I'd like to work on this issue

**Comment by ffiesta** [comment]
It's a good idea. I will try to make this
