### ISSUE TITLE
Collapsible does not support embedded markdown

### ISSUE THREAD

**Issue by kopax** [Zavy86/WikiDocs#202]
### Describe your issue

When using a collapsible, in the preview while editing in display well the markdown, but when I save, the collapsible content is not markdown processed

### Device and settings

Docker image latest version

### Steps to reproduce

Use the example from github, add markdown, preview show the content formatted with markdown, save, preview show raw text.

### Screenshots (optional)

When editing with preview:

![image](https://github.com/user-attachments/assets/a4550772-4354-42c7-ae1a-5de9617a1add)

When published: 

![image](https://github.com/user-attachments/assets/5eae3db1-5d0f-4b97-8d71-d9aadeda8b0c)

### Extra fields

- [ ] I'd like to work on this issue

**Comment by ffiesta** [comment]
Hi, collapsible dont work with block code, but work with 1 line  code.

**Comment by leomoon** [comment]
yea, I'll work on this soon.

**Comment by leomoon** [comment]
this is WAY more complex that it seems.

I made it work with both details and +++ tags as collapsible section. BUT details would indent the elemnts inside and that confuses parser as a code block!!!

but if the elements insid details are not indented it renders properly in the new version which is not out yet.

**Comment by leomoon** [comment]
another issue is that if you indent codeblock, it would show in rendering. This is the same issue with Confluence.

But it is rendering markdown inside `details` and `+++` tags and it is better not to indent tags except lists...

![image](https://github.com/user-attachments/assets/ac228a63-bc1c-490b-8c99-1b58c2da69c0)

**Comment by kopax** [comment]
Wow, I am glad you check that issue, as this is really giving me hard time to hide some informationf on long page such as technical specifications. 

> but if the elements insid details are not indented it renders properly in the new version which is not out yet.

That's not a problem for me, I will just follow the convention, but I guess it can be problem for others.

> But it is rendering markdown inside details and +++ tags and it is better not to indent tags except lists...

I am not sure what's your syntax here, would you mind sharing a code snippet that I can test?

> Also the editor's viewer cannot display these properly. Editor is a library done by someone else. we might need to improve the editor later.

Same, it's not a problem, this is a hedge case and any temporary solution is already a game changer for daily use of current version.

**Comment by leomoon** [comment]
forgot to close this. This is fixed.
