### ISSUE TITLE
Collapsible does not show text correctely

### ISSUE THREAD

**Issue by ffiesta** [Zavy86/WikiDocs#208]
### Describe your issue

Hi, 

I have this text "Procurar o perfil, normalmente é o que tem subfolders;" in collapsible it show **é** with **ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ©** however in without collapsible it's fine.

![image](https://github.com/user-attachments/assets/73293d2b-658a-454e-8716-b2bab93fe1b3)

### Device and settings

WIndows 10 Pro, Chrome browser

### Steps to reproduce

Wite text on collapsible.

### Extra fields

- [ ] I'd like to work on this issue

**Comment by leomoon** [comment]
I did HOURS of testing.

It is ParsedownExtra that is screwing up the unicode!!!

I'll see if I can fix parsedownExtra.

**Comment by leomoon** [comment]
fixed in [1.0.63](https://github.com/Zavy86/WikiDocs/releases/tag/1.0.63)
