### ISSUE TITLE
annoying error - not_authenticated

### ISSUE THREAD

**Issue by ffiesta** [Zavy86/WikiDocs#218]
### Describe your issue

After update wikidocs to 1.0.65 after 5 minutes i receive errro "not-authenticated", and I need to insert password! This is annoying because if you are in idle on a wiki, you are logged out and need to start again your work despite recovering the information from draft.md.

![Erro wikidocs](https://github.com/user-attachments/assets/e4117a5b-3a47-4178-b700-1bfe2f1d9594) 

I solve this issue change from 300 to 3600, **line 45** of **classes/Session.class.php** file, but after 1 hour e need to inser again password!

I say that it's annoying, because we lost time insterting again password, and again, and need to start again avery time it logout user from session!

### Device and settings

Windows 10 Pro, chrome browser

### Steps to reproduce

1. Login in wiki docs
2. start writing big wiki file
3. after 5 minutes receive "not_authenticated"

### Extra fields

- [ ] I'd like to work on this issue

**Comment by leomoon** [comment]
that's good.

do you want to create an MR with that `3600` change?

**Comment by ffiesta** [comment]
> that's good.
> 
> do you want to create an MR with that `3600` change?

I know that this change is because XSS Xbow security, but insert 3 times password to write simple wiki or faq it's bad! I don't know if it's good way, because after 1 hour the problem repeats itself! ...and if we had multiple users writing same wikidocs in same time, all users are logged out! 

In my opinion wikidocs should renew automatically to 5 minutes session is detects user interact or show popup asking to user confirmation renew session or something that won't logout user in 1h session!

**Comment by ffiesta** [comment]
> 3600 is fine to change.
> 
> do you wanna create a merge request?

Done! Pull request :-)
