### ISSUE TITLE
Invalid tmp_name

### ISSUE THREAD

**Issue by ffiesta** [Zavy86/WikiDocs#225]
### Describe your issue

I won't know it it is related with another login error, but my php say 

`[04-Dec-2024 14:16:49 UTC] PHP Warning:  Undefined array key "tmp_name" in /home/example/public/example.pt/submit.php on line 304`

### Device and settings

Cpanel

### Steps to reproduce

Read error_log file on root of wikidocs

### Extra fields

- [ ] I'd like to work on this issue

**Comment by leomoon** [comment]
what were you naming the doc?

**Comment by leomoon** [comment]
no I mean, when saving, what was the name of your doc?

**Comment by ffiesta** [comment]
> no I mean, when saving, what was the name of your doc?
> 
> did this happen when saving a new doc or editing an existing doc or something else?

I won't remember, but i remember wikidocs freeze when try to save.

Sorry!

I need to kown the file name, and what I was doing!? Write!?

**Comment by leomoon** [comment]
yea cuz line 304 in php is where it checks for filename and removes spaces with dashes. so that's why I tought it might be some strange unicode character in your doc name that makes it go crazy. But that's just a guess.

**Comment by ffiesta** [comment]
I will check, again ... 

There is some simple way to insert some kind of code in wikidocs, that when detect a error_log file show a warning. In this way it more easy to identify some error

**Comment by ffiesta** [comment]
Thanks,

I add `if (file_exists('error_log')) {echo " &#9888;" ;} ` to footer to show a warning if wikidocs create a erro_log file. Thanks
