### ISSUE TITLE
Suggestion: Use EasyMDE and ParsedownExtended

### ISSUE THREAD

**Issue by ByteSturm** [Zavy86/WikiDocs#26]
Hey, I'm currently playing around with the tool. 

I noticed that you are using SimpleMDE and Parsedown to edit and display the md files. I suggest using [EasyMDE](https://github.com/Ionaru/easy-markdown-editor) instead of SimpleMDE as SimpleMDE is not actively developed anymore. 

Also I suggest using [ParsedownExtended ](https://github.com/BenjaminHoegh/ParsedownExtended) in addition to Parsedown as it comes with many handy features for a wiki / documentation tool and is able to display KaTeX as requested in issue [16](https://github.com/Zavy86/WikiDocs/issues/16) :)

**Comment by Zavy86** [comment]
thank you so much for the tips.
as soon as I have a moment I'll try!

**Comment by Zavy86** [comment]
Replaced SimpleMDE with EasyMDE in branch [/feature/easy-markdown-editor](https://github.com/Zavy86/WikiDocs/tree/feature/easy-markdown-editor)

**Comment by Zavy86** [comment]
Replaced Parsedown and add Extra
