### ISSUE TITLE
Bad render header/tags

### ISSUE THREAD

**Issue by damufo** [Zavy86/WikiDocs#27]
![imaxe](https://user-images.githubusercontent.com/4057369/150785042-63fe625a-66ca-47f0-85a0-188651a5b551.png)

![imaxe](https://user-images.githubusercontent.com/4057369/150785119-073638b4-1799-47e1-92e3-f5b23d69f2e3.png)

Header 1 is a # followed by a space.

When #diary is rendered as a header and should not.

Very thanks for your work.

**Comment by Zavy86** [comment]
hi, there must be an error in the markdown parsing library.
I will have to update it for other requests, I hope this will be resolved too.. ;)

**Comment by Zavy86** [comment]
Parsedown issue: https://github.com/erusev/parsedown/issues/827

**Comment by Zavy86** [comment]
hi, it seems to be a solvable problem with the next version of parsedown, with the beta of version 1.8 it works correctly.
However I prefer to wait for the official release before updating the libreriea included in wikidocs.

![image](https://user-images.githubusercontent.com/2051811/154285929-01b154bb-ed41-4e9c-9f2c-01d428d4dd81.png)

**Comment by Zavy86** [comment]
Fixed
