### ISSUE TITLE
mobile version, edititng and saving a page won't really save the edits.

### ISSUE THREAD

**Issue by aguaviva** [Zavy86/WikiDocs#29]
It fails in both mobile Firefox and Chrome. 
On the cellphone forcing desktop version all works fine.
On desktop Firefox all works fine.

Used latest main version. Chances are the issue is in the editor module.
Cheers and thanks for this great app :)

edit: please let me know if this is enough, otherwise I will share a screen recording with you.

**Comment by aguaviva** [comment]
I could repro with your demo, here is a video showing the issue:

https://user-images.githubusercontent.com/5200915/163736047-19fb4213-e363-4bd5-952a-74eccbc92afd.mp4

**Comment by Zavy86** [comment]
Grazie per la segnalazione, controllerò! ;)

**Comment by aguaviva** [comment]
Fantastico! :)

**Comment by aguaviva** [comment]
Hi @Zavy86, I was wondering whether you had any chance to look a this :) I can't wait to use WikiDocs :)

**Comment by Zavy86** [comment]
Hi, can you try the version on branch **feature/easy-markdown-editor** please?

I have replaced SimpleMDE with EasyMDE.

https://github.com/Zavy86/WikiDocs/tree/feature/easy-markdown-editor

Thank you!

**Comment by Zavy86** [comment]
ok then I'll make an official release!

Thank you for the test!

**Comment by aguaviva** [comment]
Actually, I was too fast there, it turns out it is not saving the updates. I need to add a crlf in order for the edits to get saved.

**Comment by aguaviva** [comment]
I am looking into this but I cant find the root cause. Any idea what is different in the mobile version that could be causing this issue?

**Comment by smithj33** [comment]
Just seeing if this can be revived. Mobile editing doesn't save as said above and it duplicates words when trying to edit. I switched to the Desktop setting on Firefox and Chrome and it has some issues with saving and editing as well, so just something with mobile browsers. Thanks

**Comment by aguaviva** [comment]
I'd be surprising that all mobile browsers had the same bug. Could it be the app is doing something different when using mobile layouts?

**Comment by aguaviva** [comment]
editing pages on the cellphone is still glitchy

**Comment by Zavy86** [comment]
now it seems to work, at least with my google pixel..

![Screenshot_20230504-084757](https://user-images.githubusercontent.com/2051811/236131009-944c67f0-0c91-4138-9f25-dab10784b236.png)

![Screenshot_20230504-084802](https://user-images.githubusercontent.com/2051811/236130999-2a9a638e-6f18-42ed-823c-e13117f35f08.png)
