### ISSUE TITLE
images don't show up

### ISSUE THREAD

**Issue by aguaviva** [Zavy86/WikiDocs#30]
They get uploaded and saved in the folder of the page but they don't show up

**Comment by Zavy86** [comment]
can you try in the online demo?

**Comment by raulamd** [comment]
Pasting an image works fine in the online demo. 
Dropping an image didn't work though.

So glad to see this project is alive!! :)

**Comment by Zavy86** [comment]
Hi, I have try in the online demo both with paste and browse from file and it works.
What is the file extension that are you trying to upload?

**Comment by serial** [comment]
Hi guys, I have also tested it in the online demo.
- Copying from snipping tool and pasting directly via ctrl+v (paste) in the editor - works.
- Dropping an image (.png) from windows explorer into the area - nothing happens, no error at all.
- Trying to copy from windows explorer (right click at the image -> copy) and pasting it with ctrl+v also nothing happens. I think it`s the same action as dropping is recognized.

Zavy what did you mean by saying "browse from file works", you mean the dropping into the editor is working on your side?

It seems that there are some different actions:
1. Copy via hotkeys from clipboard to the editor. This is handled by the `images.js` (window.addEventListener("paste",function(e)...)
2. Dropping files (drag n drop) into the editor, commonly this is handled by the editor itself. I couldn`t find any listener in the images.js for this. 
3. Editor upload dialog (not active, not tested)

> If you enable `uploadImage: true` in the `editor.js`
> And if you now try to paste from clipboard, for example from the snipping tool
> 1. It comes an alert.error dialog which says: `"Something went wrong when uploading the image <filename>.<filetype>.` 
> 2. The console is showing: "EasyMDE: The server did not return a valid json.".   
> 3. You can see your catched error from your `images.js` which is: {"error":null,"code":"image_uploaded","name":"62c74fa1982e664783dcab885948324d.png","path":"\/documents\/testing\/62c74fa1982e664783dcab885948324d.png","size":22211}  
> - As result the image is created (submit.php?act=image_upload_ajax) in the folder and the link is inserted as expected.

Unfortunately, I haven't had time to analyze it in more detail at the moment, but maybe it points you in the right direction of the image.js file.

**Comment by Zavy86** [comment]
to upload an image you can use the blue icon in the top right of the edit
page. in this modal window you can browser an image from your file system
and upload It.
drago and drop feature is not enable at this moment.


Il lun 19 set 2022, 20:05 Micha ***@***.***> ha scritto:

**Comment by serial** [comment]
Ok, now I understand. The blue image-icon button is working perfectly!
Then raulamd means the drag and drop feature, which is not supported yet.

**Comment by aguaviva** [comment]
I meant that 
- pasting an image from the clipboard worked
- drag and dropping an image from a folder didn't work.

**Comment by Zavy86** [comment]
drag and drop feature is not implemented yet

**Comment by aguaviva** [comment]
Note that if you flag it as "completed" it means that the issue has been fixed/implemented.  Note that the front page still claims this is an existing feature, you may want to under-promise and over-deliver (and not the other way around)

**Comment by aguaviva** [comment]
This is still happening as of today.
