### ISSUE TITLE
REFACTORING

### ISSUE THREAD

**Issue by Zavy86** [Zavy86/WikiDocs#31]
Hi everyone, I'm going to do a major refactoring of Wiki|Docs.
If you are interested in contributing to this project leave a reply in this thread.
Thanks for all!

Watch Wiki|Docs presentation and contributors recruitment on YouTube:
[![Wiki|Docs presentation and contributors recruitment on YouTube](https://wikidocs.it/documents/homepage/cover-side-project-wikidocs-youtube.jpg)](https://www.youtube.com/watch?v=NFILGeozt7k "Watch Wiki|Docs presentation and contributors recruitment on YouTube")

**Comment by aguaviva** [comment]
Fantastic, I cant wait to test your new version :)

**Comment by Zavy86** [comment]
if anyone wants to participate/test in the refactoring, the branch is: https://github.com/Zavy86/WikiDocs/tree/refactoring

**WARNING**

```
configuration, documents and trash are moved into a new datasets directory.
backup everything before upgrading
```
