### ISSUE TITLE
Improvement: choose language on setup

### ISSUE THREAD

**Issue by jv3ga** [Zavy86/WikiDocs#34]
There's no so many menus and options, but it would be nice to choose the language. Once you put the mechanism to do so I can (want) to help you to translate it to spanish.

**Comment by Zavy86** [comment]
hi @jv3ga, i'm working on it..
i have added a settings page and i will add a menu to choose language.
when i have the file to translate I will notify you if you are still interested.
branch: https://github.com/Zavy86/WikiDocs/tree/refactoring

**Comment by jv3ga** [comment]
Of course! I will be glad to help.

**Comment by Zavy86** [comment]
Hi @jv3ga can you translate the right side of this file?
https://github.com/Zavy86/WikiDocs/blob/master/localizations/en.json
Thank you!

**Comment by jv3ga** [comment]
Awesome! I'll make a pull request when it's readyAwesome! I'll make a pull request when it's ready

**Comment by jv3ga** [comment]
Awesome! I'll make a pull request when it's ready
