### ISSUE TITLE
Homepage/

### ISSUE THREAD

**Issue by StarRico** [Zavy86/WikiDocs#4]
Is there anyway to drop the homepage/ part of the url? I wouldn't want everything having the homepage/ in the url... for example... a subject i'd prefer to see (domain name)/(page name)

**Comment by Zavy86** [comment]
certo.
hai creato le pagine sotto alla homepage.
dovresti creare le pagine al livello superiore.

for example https://www.wikidocs.it/demo?edit

instead of for example https://www.wikidocs.it/homepage/demo?edit

it works?
