### ISSUE TITLE
uploading images in the demo doesn't work

### ISSUE THREAD

**Issue by aguaviva** [Zavy86/WikiDocs#40]
I can edit the text and dropping text files will include their contents into the page, but dropping images wont do anything.

**Comment by Zavy86** [comment]
it's a docker volume problem.. i need to fix it

**Comment by aguaviva** [comment]
No offense but you have been advertising this project in different platforms for over a year, and yet there is basic functionality that never worked. This is not making you look any good. I know this is open source and free, but still you shouldn't say things that undermine your credibility.

**Comment by Zavy86** [comment]
hi @aguaviva, have you tried to download the latest version via docker?
as you can see from the demo it works now.
If you still have the problem, try to clarify it better.

![Screenshot 2023-04-25 at 15 52 50](https://user-images.githubusercontent.com/2051811/234298678-0152364a-27f7-40c4-bca3-42543f04c413.png)
