### ISSUE TITLE
If the sidebar and homepage can be customized for sorting; Will be even better

### ISSUE THREAD

**Issue by ydyi** [Zavy86/WikiDocs#41]
If the sidebar and homepage can be customized for sorting; Will be even better
![Snipaste_2023-04-20_14-13-17](https://user-images.githubusercontent.com/38550578/233274197-8bd7f704-0479-45c9-a967-8ee34090104f.png)

**Comment by Zavy86** [comment]
Hi @ydyi at the moment the sorting is alphabetically, so you can use numbers.
After the refactoring in final version the menu will be completely customizable.

**Comment by ydyi** [comment]
That's great!
