### ISSUE TITLE
OL and UL preview is broken when editing in version 0.5.0

### ISSUE THREAD

**Issue by leomoon** [Zavy86/WikiDocs#47]
OL has too much padding and UL doesn't have the bullet.

I tried to figure this out but I still don't know why this is happening!

![image](https://user-images.githubusercontent.com/3268946/236940860-e132faa6-bb55-4121-8ba9-113d05f38707.png)

**Comment by Zavy86** [comment]
resolved?

**Comment by leomoon** [comment]
oh yea this is good now.
