### ISSUE TITLE
top buttons don't show the images in firefox on my system

### ISSUE THREAD

**Issue by howardlshippin** [Zavy86/WikiDocs#48]
![Screenshot_20230509_015647](https://user-images.githubusercontent.com/105754379/236955162-a81877fa-bd94-41bf-886c-cc7b2b52dd28.png)
The tooltips make their function obvious, and it might be possible to fix this in css. 
In Vivaldi browser, the button images show, in firefox not.
This may be related just to my operating system (MX Linux), as I think I have a similar problem in another web server application.

**Comment by Zavy86** [comment]
Hi @howardlshippin, have you tried to force reload?
maybe it didn't load the css fonts correctly.
we have moved many files

**Comment by howardlshippin** [comment]
Yes, tried that.  Also I did the update from  0.4.4   The instructions for a manual update say to move the documents and trash and configuration file to a new directory, datasets.  I did all that, but after logging in, there was a new blank configuration file.  After configuring, I saw that the existing wiki files were not found.  So I renamed the configuration file and the documents directory, and moved the old documents directory and configuration file back into the wikidocs directory.  Was that the right thing to do?  anyway it works for now (still no button images).

**Comment by Zavy86** [comment]
@howardlshippin can you try this workaround?

https://forum.manjaro.org/t/material-design-icons-not-showing-in-firefox/88882

**Comment by howardlshippin** [comment]
Thanks.  In my case, the solution was to disable the Firefox plugin Privacy Badger for the website. On the other hand, I'm not so happy with the solution.  I think it would be better to include the fonts directly, since remote fonts can be used as trackers.  The WordPress theme that I use on another site recently began to download Google Fonts directly to the site, rather than serving them remotely.  And they say that this is in order to comply with EU privacy laws.

**Comment by Zavy86** [comment]
ok i have include it in release 0.5.3.. @howardlshippin can you try now?

**Comment by Zavy86** [comment]
hi, commands for git update are git stash and git pull.
it would be recommended to use docker.
for upgrade script open a new issue please..

buttons are ok now? can I close this issue?

**Comment by howardlshippin** [comment]
and thanks for your help.
