### ISSUE TITLE
homepage was not created & does not seems to work

### ISSUE THREAD

**Issue by wallyreport** [Zavy86/WikiDocs#5]
I filled out all of the config stuff. Got all green checkmarks. Clicked "continue" but it could not find homepage. 

I created a homepage directory. But I just get an index when I try to go there.

**Comment by Zavy86** [comment]
You don't need to create and other directory.
Check for the .htaccess file

Il mer 15 gen 2020, 19:45 wallyreport <notifications@github.com> ha scritto:
