### ISSUE TITLE
Error 404 Page not found

### ISSUE THREAD

**Issue by wallyreport** [Zavy86/WikiDocs#6]
I am running debian.

I downloaded the zip file and unzipped in /var/www/html

I changed the name of Wikidocs-master directory to wikidocs

After running setup.php. The .htaccess was not created, so I created it by copy-pasting the .htaccess you posted. 

Also no homepage directory was created, so I created one.

I go to either localhost/wikidocs or /localhost/wikidocs/index.php
And I get: 

> Error 404
> We are sorry but the page you are looking for does not exist.
> Click the edit button to create this page!

The edit button takes me to:

> http://localhost/wikidocs/homepage/?edit
> Index of /wikidocs/homepage

**Comment by Zavy86** [comment]
Try deleting the homepage directory and check in the configuration file for
the path
and copy the same path into the .htaccess file. This week i can't access to
my PC. Next week i can help you more..

Il mer 15 gen 2020, 20:26 wallyreport <notifications@github.com> ha scritto:

**Comment by wallyreport** [comment]
The path from config.inc.php and .htaccess seems to be the same:

From config.inc.php

> define("PATH","/wikidocs/");

From .htaccess 

> RewriteBase /wikidocs/

When I delete the homepage directory, then click on the icon to authenticate, I get:

> Not Found
> The requested URL was not found on this server.
> Apache/2.4.41 (Debian) Server at 192.168.1.9 Port 80

**Comment by Zavy86** [comment]
Check for mod_rewrite. Try to execute  the shell command # a2enmod rewrite and restart apache.

**Comment by wallyreport** [comment]
```
# a2enmod rewrite
Enabling module rewrite.
To activate the new configuration, you need to run:
  systemctl restart apache2
# systemctl restart apache2
```
Still does not work.

This is my /var/www/html/wikidocs directory:
```

# tree
.
├── classes
│   ├── Document.class.php
│   ├── index.php
│   └── WikiDocs.class.php
├── config.inc.php
├── config.sample.inc.php
├── css
│   ├── index.php
│   └── styles.css
├── documents
│   ├── homepage
│   │   └── content.md
│   └── index.php
├── functions.inc.php
├── helpers
│   ├── index.php
│   ├── jquery-3.3.1
│   │   ├── js
│   │   │   ├── jquery.js
│   │   │   └── jquery.min.js
│   │   ├── LICENSE.txt
│   │   └── README.md
│   ├── materialize-1.0.0
│   │   ├── css
│   │   │   ├── materialize.css
│   │   │   └── materialize.min.css
│   │   ├── js
│   │   │   ├── materialize.js
│   │   │   └── materialize.min.js
│   │   ├── LICENSE.txt
│   │   └── README.md
│   ├── parsedown-1.7.1
│   │   ├── LICENSE.txt
│   │   ├── Parsedown.php
│   │   └── README.md
│   ├── priss-0.0.1
│   │   ├── css
│   │   │   └── print.css
│   │   ├── LICENSE.txt
│   │   └── README.md
│   └── simplemde-1.11.2
│       ├── css
│       │   ├── simplemde.css
│       │   └── simplemde.min.css
│       ├── js
│       │   ├── simplemde.js
│       │   └── simplemde.min.js
│       ├── LICENSE.txt
│       └── README.md
├── images
│   ├── favicon.png
│   └── index.php
├── index.php
├── js
│   ├── editor.js
│   ├── images.js
│   ├── index.php
│   └── initializations.js
├── LICENSE.txt
├── print.inc.php
├── README.md
├── setup.php
├── submit.php
├── template.inc.php
├── update.php
└── VERSION.txt

```
