### ISSUE TITLE
non rewrite flavour ?

### ISSUE THREAD

**Issue by mckaygerhard** [Zavy86/WikiDocs#64]
any way to avoid rewrite, vendors sometimes dont allow this!

or at leas any way to made it using internally or to bypass to educationall use

**Comment by Zavy86** [comment]
hi @mckaygerhard, given how the wiki is developed today, the redirect is essential..

**Comment by mckaygerhard** [comment]
gitea can be deployed witout that crap of rewrite, mkdocs and mkwiki also, why this not.. in that case this is non usefuilly .. cos forced anybody to deploy a specific server.. what a disappointment
