### ISSUE TITLE
drag and dropping images does not work

### ISSUE THREAD

**Issue by aguaviva** [Zavy86/WikiDocs#67]
I just tested this in your online demo

**Comment by nicolas35380** [comment]
Hi,
I think this functionnality is (not yet ?) implemented. To insert a image, you can :

- Clic on "Insert Image" button from tollbar and link it with Markdown Editor
- Past from clipboard

**Comment by Zavy86** [comment]
> I think this functionnality is (not yet ?) implemented.

and is not in the current roadmap..
