### ISSUE TITLE
No "homepage?auth"

### ISSUE THREAD

**Issue by wallyreport** [Zavy86/WikiDocs#7]
I tried another version. 

This time WikiDocs-0.1.8.zip instead of WikiDocs-master.zip
When I tried to login, it looked for "homepage?auth" but there is no "homepage"  directory, and there is no "auth" anything anywhere.

**Comment by Zavy86** [comment]
Wikidocs work with a single entry point in the index file with a rewrite
rule in the .htaccess file. If the rewrite rule is not enabled It can't
work..

Il mer 15 gen 2020, 21:56 wallyreport <notifications@github.com> ha scritto:

**Comment by wallyreport** [comment]
I copied the .htaccess out of the README.md file.

```
<IfModule mod_rewrite.c>
	RewriteEngine On
	RewriteBase /wikidocs/
	RewriteCond %{REQUEST_FILENAME} !-f
	RewriteRule ^(.*)$ index.php?doc=$1 [NC,L,QSA]
</IfModule>
```
The .htaccess file is located in the `/var/www/html/wikidocs` directory. I have also tried putting in the `/var/www/html` directory.

**Comment by Zavy86** [comment]
the virtual host is defined to the directory `var/www/html/` ? 

your wikidocs url is http://localhost/wikidocs?

in this case the .htaccess file need to be placed in `/var/www/html/wikidocs/.hhtaccess`

and the content should be

```
<IfModule mod_rewrite.c>
	RewriteEngine On
	RewriteBase /wikidocs/
	RewriteCond %{REQUEST_FILENAME} !-f
	RewriteRule ^(.*)$ index.php?doc=$1 [NC,L,QSA]
</IfModule>
```

the configuration file should be

```
[...]
define("PATH","/wikidocs/");
[...]
```

------

or if you have a virtual host to the directory `/var/www/html/wikidocs/`

and your wikidocs is accessible by http://localhost/  (without /wikidocs)

the .htaccess file need to be placed in `/var/www/html/wikidocs/.hhtaccess`

but the configuration file and the htaccess need to be 


```
[...]
define("PATH","/");
[...]
```

```
[...]
	RewriteBase /
[...]
```

**Comment by wallyreport** [comment]
The .htaccess file is in the right place, and the configuration file is as you describe. I am not using a virtual box.

**Comment by Zavy86** [comment]
What is your os and php version?

**Comment by wallyreport** [comment]
I am using ParrotOS which is based on Debian.

```
#uname -a
Linux fir.nuclix 5.3.0-3parrot3-amd64 #1 SMP Parrot 5.3.9-3parrot3 (2019-11-23) x86_64 GNU/Linux

#php -v
PHP 7.3.12-1 (cli) (built: Nov 28 2019 07:34:08) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.12, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.12-1, Copyright (c) 1999-2018, by Zend Technologies

```

**Comment by Zavy86** [comment]
Try to check in the apache site configuration if the directory allow the overrides, my configuration is:

```
 <Directory /var/www/wikidocs>
    Options -Indexes +FollowSymLinks +MultiViews
    AllowOverride All
    Order Deny,Allow
    Allow from all
</Directory>
```
