### ISSUE TITLE
Mermaid Diagrams Support ?

### ISSUE THREAD

**Issue by accforgithubtest** [Zavy86/WikiDocs#73]
### Describe the feature

Any chances of getting mermaid diagrams support in WikiDocs (similar to markdown preview enhanced) ? 

### Is your feature request related to a problem? (optional)

Diagramming features in markdown

### Extra fields

- [ ] I'd like to work on this feature

**Comment by Zavy86** [comment]
hi, something had already been implemented..
you've tried? Is there something not working for you?

https://github.com/Zavy86/WikiDocs/pull/52

**Comment by Zavy86** [comment]
@accforgithubtest any news?
