### ISSUE TITLE
Link to headers in pages

### ISSUE THREAD

**Issue by filipesaraiva** [Zavy86/WikiDocs#74]
### Describe the feature

I started to use WikiDocs and this project is amazing, thanks!

Is that possible to have links to headers inside the pages? For example, I have a page with Header 1, subheader 1, subheader 2, etc. I would like to have a link to subheader 2 directly.

Thank you!

### Extra fields

- [ ] I'd like to work on this feature

**Comment by Zavy86** [comment]
Hi Filipe, do you mean the possibility of making a link that refers to a specific header?
For example: http://wikidocs.it/page_name#header_name ?

**Comment by Zavy86** [comment]
@filipesaraiva ?

**Comment by jv3ga** [comment]
I come around here to check if somebody asked for the same feature, I think is exactly what you say @Zavy86

**Comment by Zavy86** [comment]
ready!

https://wikidocs.it/documentatation/configuration#2-2-1-manual

you can view the anchor link as a title of the header

![image](https://github.com/Zavy86/WikiDocs/assets/2051811/e03a929b-a228-4d02-8c00-df81b71f5a0c)

;)
