### ISSUE TITLE
Upgrade to PHP8 version in dockerfile since PHP7 is EOL

### ISSUE THREAD

**Issue by MoritzGiessmann** [Zavy86/WikiDocs#78]
https://github.com/Zavy86/WikiDocs/blob/5aa28ca021bd4bead9925c8b625f701570ad46b1/docker/production.dockerfile#L20

**Comment by Zavy86** [comment]
we can think about changing the version of php in the docker distribution, but for backwards compatibility I would prefer to leave the source code also compatible with php 7.
