### ISSUE TITLE
How do I change the authentication code? 

### ISSUE THREAD

**Issue by wallyreport** [Zavy86/WikiDocs#8]
Wiki will not accept anything I input for authentication code. I have root access, can I change config.inc.php, or something?

**Comment by wallyreport** [comment]
Never mind. I just re-installed

**Comment by Zavy86** [comment]
Yes you can edit the password in config.inc.php
The password should be stored in md5 format

**Comment by Zavy86** [comment]
> Is this still valid? It doesn't look mike a md5?!

the initial password is password.

you can change it in md5 format and then if you change it in settings will be updated to the new encryption method

**Comment by k9ert** [comment]
I've figured it out:
It's now using bcrypt by default. So you can use https://bcrypt-generator.com/ to encrypt your password and place that string in the config.inc.php.
