### ISSUE TITLE
Newlines in page content are not displayed correctly

### ISSUE THREAD

**Issue by freekbe** [Zavy86/WikiDocs#82]
### Describe your issue

When using newlines in a page content, it all looks fine in the editor and also in the preview. But when the content is saved and the page is displayed in read-mode, the newlines are ignored.

When editing the page again, the newlines are still there in the editor and preview, so they are not removed from the content.

### Device and settings

nginx: 1.22.1  PHP: 8.2.7

### Steps to reproduce

1. Install WikiDocs on nginx 1.22.1 with PHP version 8.2.7
2. Edit / add some page content with newlines
3. Save the page

### Screenshots (optional)

![image](https://github.com/Zavy86/WikiDocs/assets/16103542/47a46527-ac5a-4bfb-9875-774a42c7fab9)
![image](https://github.com/Zavy86/WikiDocs/assets/16103542/55a95b9b-5f86-441e-94cf-2d726675992a)

### Extra fields

- [ ] I'd like to work on this issue

**Comment by freekbe** [comment]
FYI: I'm running WikiDocs 1.0.9

**Comment by Zavy86** [comment]
hi, this is not a bug, is a markdown implementation.
to make multiple paragraph you need to use a double new line.
or i you want to make your paragraph to two lines you need to add two spaces after the first line:
https://www.markdownguide.org/basic-syntax/#line-breaks

Let me know if you succeeded or if you have any other problems

**Comment by freekbe** [comment]
Hi, thanks for the response.
I'm not trying to create paragraphs, those are working fine.
However, newlines are being ignored (see the second screenshot)

**Comment by Zavy86** [comment]
check the demo site before resetting :D
https://demo.wikidocs.it/

![image](https://github.com/Zavy86/WikiDocs/assets/2051811/17dde47d-7503-48f0-a85e-795166592de8)

**Comment by freekbe** [comment]
Thanks, I get it now :-)

Thanks for all the effort, I really like this project!

**Comment by DiavoloRosso** [comment]
Mi scuso se intervengo in un issue chiuso, ma secondo me se si pubblicizza un'editor wysiwyg, questo poi lo deve essere a pieno.
Se mentre scrivo vado a capo, l'implementazione dei due spazi a fine linee deve essere automatica, in modo che salvando quello che vedo è quello che avrò (a maggior ragione se anche l'anteprima, propone già la riga a capo) . Altrimenti non è wysiwyg, è solamente un editor markdown che prevede che io conosca strettamente la sintassi markdown.

**Comment by Zavy86** [comment]
giusta osservazione, sarebbe da capire se si può fare qualcosa in fase di
salvataggio, ma in ogni caso l'anteprima sarebbe errata o se chiedere
direttamente nella repository dell'editor di aggiungere questa funzione..
vedo cmq che ci sono nuove release dell'editor proverò ad aggiornare..
