### ISSUE TITLE
Dark Mode cannot be enabled?

### ISSUE THREAD

**Issue by bverkron** [Zavy86/WikiDocs#83]
### Describe your issue

Maybe I'm missing something in the readme or docs etc but the dark mode checkbox is the settings is not checkable. Nothing happens when I click it.

I went into the page HTML and added the 'checked' property and saved and it enabled dark mode but I have not idea why it isn't checkable in the webpage normally.

### Device and settings

Client: Safari & Brave (i.e. Chrome) on macOS. Server: latest version of WikiDocs via :latest tag

### Steps to reproduce

Go into Settings and try to check the Dark mode box.

### Screenshots (optional)

n/a

### Extra fields

- [ ] I'd like to work on this issue

**Comment by Zavy86** [comment]
fixed in v1.0.11
