### ISSUE TITLE
[Feature Request] Allow custom markdown file names (other than content.md)

### ISSUE THREAD

**Issue by bverkron** [Zavy86/WikiDocs#84]
### Describe the feature

Loving WikiDocs so far! It has basically all the features I need and functions the way I want / expect vs others like OtterWiki and flatnotes

The one thing in my early testing that makes it feel a bit "proprietary" is the file structure. It seems to force each markdown file to be called content.md and be in it's own folder.

While I see the organizational advantages to this it makes it difficult to port over markdown from other tools such as Otter or flatnotes or vice versa. It locks you into the paradigm used by WikiDocs, which feels like it defeats a bit of the purpose of using an open standard like markdown because the function and portability of the content is almost database like.

It would be great if WikiDocs at least could "read" any markdown file in the folder structure and add it to the navigation bar and allow editing of those files.

### Extra fields

- [ ] I'd like to work on this feature

**Comment by Zavy86** [comment]
the directory structure is quite complicated to change at the moment.
Could it be an idea to create an import tool?

**Comment by bverkron** [comment]
What I had in mind should not require major changes to the directory structure, just allowing names other than `content.md` for the file in the root of the page directory. For example it could just look for any `.md` file in the directory instead of only one named `content.md`. When creating new page it could just use the name of the first heading tag in the document as the default name for the file (with - replacing spaces, etc) and/or allow the user to name the file when doing the first save.

Some background on why I think this change would be helpful:

In addition to better "portability" between markdown apps and a more open "standard" (if you want to call it that) it would make things a bit more readable when modifying / organizing things manually in the file system, since currently it does not appear to be possible to reorganize pages in the UI. Although the folder name is a good indicator of the page contents working with multiple files called `content.md` in an editor or file browser makes it easier to make mistakes since it's harder to distinguish between the files based on name alone.

For example I'm currently using VS Code to reorganize the page hierarchy and do some page edits while I'm in there and having multiple pages open in the editor is confusing because each tab is named `content.md`

This is by no means a critical or important feature IMO and only a minor annoyance but I do think it would give more flexibility when moving to / from WikiDocs.

An importer could work but it would probably be more work that what I'm suggesting (i.e. allowing filenames other than `content.md`), it would not solved some of the issues described above, and with an almost infinite number of ways the incoming markdown files could be structure and named it may be hard to make a "universal" importer easily.

**Comment by nomandera** [comment]
I just wanted to feedback that this was a show stopper for adoption for me. Like most I have a legacy of previous wiki solutions attempting to find something elegant and maintained (i.e. from lionwiki to raneto to gitea) all are traditional path and filename layout wikis and therefore not compatible with WikiDocs.

Structure is important for a filesystem based wiki and as per the OP it feels a bit "proprietary" as-is. A compromise would be a on-boarding script although thought should be given to something more like a drop in replacement when so many other projects are inherently interchangeable as they dont mandate how a user should store or name files. e.g. I would often ssh in and make notes direct with nano when on site and not able to access HTTP.

Keep up the good work. The project really fills a well needed gap and the introduction project history and demo video really is a very nice touch.

**Comment by Zavy86** [comment]
I, not in this version..
Maybe in a future refactoring..
Version 2.0+

**Comment by ffiesta** [comment]
Good,

I think that changing the name from content.md to your own name could be important, however for managing a wiki system, the most important thing is a good structure! I currently have 750 files and I don't see the need to change the mode. Yes, it's very annoying to be all content.md, but it's reliable. If it is to be changed, the option of content.md or the name of the title is provided. As my boss said, "keep it simple"
