### ISSUE TITLE
[Feature Request] Change behaviour of link creator in editor

### ISSUE THREAD

**Issue by bverkron** [Zavy86/WikiDocs#85]
### Describe the feature

In most apps when you use the feature to create a link when you have text selected (either with a menu button or a keyboard shortcut like CTRL/CMD+K) it will put the cursor in a position where you can paste in the contents of your clipboard which presumably is a URL. This makes creating a link very slick and easy after highlighting the text for the link. 

However, in WikiDocs if you select text then hit the link button or CTRL/CMD+K it keeps the original text highlighted and adds https:// into the parenthesis which means you have to manually move the cursor, delete the https, then past in the link. This is a bit cumbersome and has more room for error.

Would be amazing if it would keep the parenthesis empty and just put the cursor between them so you could just hit CTRL/CMD+V to past in the link. Much slicker!

### Screenshots (optional)

Green bar represents where the cursor would be.
![image](https://github.com/Zavy86/WikiDocs/assets/19174503/4c66c159-697e-4bd2-8fab-548348c71a8c)

### Extra fields

- [ ] I'd like to work on this feature

**Comment by bverkron** [comment]
Additional thought. Many apps go one step further and if you have a url in your clipboard and highlight the text and simply hit CTRL/CMD+V to paste it will automatically create the link for you with the highlighted text and the url from your clipboard. This is true for GitHub comments / descriptions, Confluence (which I'm migrating to WikiDocs from), Vikunja and a bunch of others. Not sure how easy that is to implement but it would be a great bonus feature on top of the behaviour suggested above.

**Comment by Zavy86** [comment]
the editor is provided by EasyMDE https://github.com/Ionaru/easy-markdown-editor, you have to create this pull request to their repository..

@leomoon we have to update to 2.18.0
