### ISSUE TITLE
Size tables based on content

### ISSUE THREAD

**Issue by bverkron** [Zavy86/WikiDocs#86]
### Describe the feature

Currently tables expand to 100% width by default and I'm not sure if there is any way to change that. I think it would be preferable in most cases to have them only be as wide as the content dictates like other wiki apps

### Screenshots (optional)

otterwiki table
<img width="293" alt="image" src="https://github.com/Zavy86/WikiDocs/assets/19174503/e98ce1a2-f1bf-4ead-8b63-207f73aae733">

flatnotes table
<img width="338" alt="image" src="https://github.com/Zavy86/WikiDocs/assets/19174503/b4219c21-8f84-4d16-8a67-cdb83021c148">

WikiDocs table
<img width="743" alt="Screenshot 2023-12-28 at 8 06 20 PM" src="https://github.com/Zavy86/WikiDocs/assets/19174503/2fa210dc-449d-4166-8153-949c055e42af">

### Extra fields

- [ ] I'd like to work on this feature

**Comment by bverkron** [comment]
While talking about tables it would also be really nice to have the header row be a bit more distinct with a background that' different from standard rows like the otterwiki example :)

**Comment by bverkron** [comment]
As a custom workaround for the width and the header background color I used the custom CSS mentioned run the readme ( I didn't see that until after submitted the FR)

```css
/* Tables */
table { width: 0; }
th{ color: white; background:#666666; font-size:1.1rem}
```

Result:
<img width="274" alt="image" src="https://github.com/Zavy86/WikiDocs/assets/19174503/3172ae87-f49f-4e8b-89df-73bd5b2df029">

I mapped the styles directory to a bind mount on the host like this.
```dockerfile
    volumes:
      - /path/on/host/wikidocs/datasets:/datasets
      - /path/on/host/wikidocs/styles:/var/www/localhost/htdocs/styles
```

I still think it would be nice to have this behaviour (or some flavour of it) out of the box so I am going to leave this FR open.

**Comment by Zavy86** [comment]
ok, i have set table witdh to 0 as you suggested.
I made a graphic customization in the style of the wiki.
if you want to change backgrounds and colors you can do as you have already understood via a custom css.
(v1.0.11)
;)
