### ISSUE TITLE
No Way to Organize Pages?

### ISSUE THREAD

**Issue by Umbyology** [Zavy86/WikiDocs#9]
First off, I love Wiki|Docs!

However, I cannot figure out a way to order the page. The pages MUST appear in a specific order, that's what wikis do, present information in a specific, "organized" way. Even when I number the pages the system does not adhere to the order.

Suggestions or fix?

**Comment by Umbyology** [comment]
Ok. So, I figured out that WikiDocs reads the first Heading in the content.md file. However, on most pages, I have an image as the first item before a heading. That screws-up the order and also erases the index name completely from the breadcrumbs and index-tree.

This is a deal-breaker for me. Any way to fix this?

**Comment by Zavy86** [comment]
Hi, is the website public? Can I see it?

**Comment by Zavy86** [comment]
Hi, if I understood correctly with version 0.1.9 I solved the problem.
Now the title is detected in any row not only in the first.

Visit page /update.php to automatically update the wiki to version 0.1.9

Let me know!

**Comment by Umbyology** [comment]
If you place an image at the top of the page (for a header or something), it yields a blank name in the table of contents.

**Comment by Zavy86** [comment]
Have you tried to update to 1.0.9 ?

**Comment by Umbyology** [comment]
I went another direction. But I may come back to this at a later date. THX for the help.
