### ISSUE TITLE
LaTeX inside editor

### ISSUE THREAD

**Issue by henrysheehy** [Zavy86/WikiDocs#95]
### Describe the feature

Dear Zavy,

Currently the preview mode displays $\LaTeX$ equations. Is it possible to implement this in the editor's own preview? I would imagine a simple insertion of js would do it. 

The editor repo appears to no longer be maintained, hence my asking here.

Gratefully,
Henry 

### Extra fields

- [ ] I'd like to work on this feature

**Comment by Zavy86** [comment]
we have migrated from simple mde to the maintened fork https://github.com/Ionaru/easy-markdown-editor try to ask in this repository..
