### ISSUE TITLE
Backup toggle tooltip suggestion

### ISSUE THREAD

**Issue by henrysheehy** [Zavy86/WikiDocs#96]
### Describe the feature

For new users, the function of the backup toggle is not clear until reading the docs. For clarity, the mouseover tooltip should display, "toggle auto-save".

### Extra fields

- [ ] I'd like to work on this feature

**Comment by Zavy86** [comment]
the backup is not the autosave function.
it backup the old version of the content before overwrite..
the autosave is always enable and will work only in the editor.

**Comment by henrysheehy** [comment]
I see. Thank you :+1:
