### ISSUE TITLE
Security question

### ISSUE THREAD

**Issue by henrysheehy** [Zavy86/WikiDocs#97]
### Describe the feature

Is WikiDocs secure enough to host personal notes on? My concern is regarding brute force attacks. 

Thank you. 

### Extra fields

- [ ] I'd like to work on this feature

**Comment by Zavy86** [comment]
no, data is not encrypted, if your note is private do not expose the wikidocs website to the web, use instead a local hosting or a vpn or other security approachs

**Comment by henrysheehy** [comment]
I see, thank you 🙏
Those concerns can be resolved via .htaccess and https , for end-to-end encryption. 
However, do you have concerns regarding injections into your demo site?
Kind regards,
Henry

**Comment by Zavy86** [comment]
wikidocs was born as a public documentation portal, password protection was a later addition, it is not to be considered a hack-proof system at the moment
